import './globals.css'
import 'bootstrap/dist/css/bootstrap.min.css';
import Header from './components/Header'
import { Mulish } from 'next/font/google'
import Footer from './components/Footer';

const mulish = Mulish({
  weight:['300','400','500'],
  subsets: ['latin'],
  display: 'swap',

})

// const roboto = Roboto({
//     weight: ['400', '700'],
//     style: ['normal', 'italic'],
//     subsets: ['latin'],
//     display: 'swap',
//     variable: "--secondary-font",

// })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={mulish.className}>
      <body>
        <Header />
        {children}
        <Footer />
        </body>
    </html>
  )
}
